
error_explaination = {
    "X01": "Check the API method is spelled correctly and that it follows immediately after the base URL, e.g. https://api.propertydata.co.uk/method-name. If in doubt, try with the example URL from the documentation first.",
    "X02": "You have not supplied an API key. Every PropertyData API call requires a key, in the querystring using the variable 'key'. If you're logged in to PropertyData, the example URLs in the API documentation are automatically populated with your API key.",
    "X03": "You supplied an API key, but it was not recognised. Check that your key is correct. Note that this is the error you would receive if you regenerated your API key in your account home, but were trying to use the old key in your application.",
    "X04": "You have reached your API plan call limit. Note that calls limits are reset at 00:01 on the first day of each calendar month. Consider upgrading your plan.",
    "X05": "The PropertyData account associated with the API key you supplied has been cancelled or had it's card declined. Login and reactivate the account if you wish to continue using the PropertyData API.",
    "X06": "You have not supplied a postcode. All API methods except 'stamp-duty' require a full UK postcode, in the querystring using the variable 'postcode'.",
    "X07": "The postcode you supplied was not recognised as a full UK postcode. Most of the time this means the postcode is not valid, although it can also mean the postcode is newly allocated. Try a different postcode.",
    "X08": "Not enough relevant data points could be found to return analytics. See 'Data collection logic' in Getting started to understand more.",
    "X09": "An unexpected error occuring in processing your API request. Please contact us, copying and pasting your API request URL.",
    "X10": "You cannot use a postcode district or sector on this method, please use only a full UK postcode.",
    "X11": "Due to source data limitations, some PropertyData API methods are only available in England or England & Wales. See the Getting started page for a breakdown.",
    "X12": "If you supply the number of points to analyse, this must be between 15 and 100. Otherwise the default of 20 will be used.",
    "X13": "During your API free trial you can only make 500. Please manually start your first month.",
    "X14": "Our terms and conditions currently ask that you make no more than one call per two second period. If you receive this message, you are calling the API too fast. Please throttle your requests.",
    "SM": "Very occasionally we take the API down for scheduled server upgrades and/or maintenance. This typically doesn't take more than one hour.",
    "102": "The value you supplied in the 'bedrooms' filter variable was not valid. Valid values are 0, 1, 2, 3, 4, 5.",
    "103": "The value you supplied in the 'type' filter variable was not valid. Consult the valid types list.",
    "401": "Stamp duty can only be calculated for prices of £1 to £10,000,000. Enter an integer in this range.",
    "402": "The value you supplied in the 'country' variable was not valid. Consult the countries list or remove the country value to use 'england' as default.",
    "403": "You entered 1 for both addtional rate stamp duty and first-time property. It is not possible for a transaction to be made both a first-time buyer and as an additional property.",
    "404": "The value you supplied for this field was not valid. Valid values for this field are: investment, primary, first_time, non_resi",
    "501": "We couldn't figure out the council from the valid postcode provided. This should not happen - please contact us us and let us know the postcode, and we will fix this.",
    "602": "Valid values for decision_rating are 'positive', 'negative' or 'neutral'",
    "603": "The valid input for max_age_decision is an integer, minimum 1, maximum 1000.",
    "604": "Planning applications were found in this area, but none that matched your filters.",
    "605": "The valid input for max_age_update is an integer, minimum 1, maximum 1000.",
    "701": "The named field is missing. All fields are required for valuations.",
    "702": "The named field is invalid. Consult the API documentation and accepted valuation options list and correct your inputs.",
    "801": "Unable to find a title number matching the title number you provided.",
    "901": "The value you supplied in the 'bedrooms' filter variable was not valid. Valid values are 0, 1, 2, 3, 4, 5.",
    "902": "The value you supplied in the 'type' filter variable was not valid. Consult the valid types list.",
    "903": "The value you supplied in the 'class' filter variable was not valid. Valid values are 'old_stock' or 'new_build'.",
    "904": "The value you supplied in the 'tenure' filter variable was not valid. Valid values are 'freehold' or 'leasehold'.",
    "905": "The value you supplied in the 'max_age' filter variable was not valid. Valid values are integers between 3 and 60 inclusive.",
    "1001": "The PTAL method is only available for Greater London postcodes, since it is a Transport for London metric.",
    "1101": "You did not provide a property list. This is required. Consult the property lists list.",
    "1102": "The 'list' provided does not match one of our lists. Consult the property lists list.",
    "1103": "The value you supplied in the 'region' variable was not valid. Consult the regions list.",
    "1104": "The value you supplied in the 'radius' variable was not valid. Radius must be an integer between 1 and 200 inclusive (miles)",
    "1105": "The value you supplied in the 'results' variable was not valid. Results must be an integer between 10 and 500 inclusive",
    "1201": "We couldn't find any schools near this postcode.",
    "1202": "Invalid filter for phase used. Accepted options are: Primary, Nursery, PRU, Secondary, Special",
    "1301": "We couldn't find any restaurants near this postcode.",
    "1401": "The value you supplied for finish quality is invalid. Allowed values are 'premium', 'medium' or 'economy'.",
    "1501": "You did not provide a number of bedrooms. This field is required for calculating LHA rate.",
    "1502": "The value you supplied in the 'bedrooms' filter variable was not valid. Valid values for this method are 1, 2, 3, 4.",
    "1601": "The value you supplied in the 'grade' filter variable was not valid. Valid values for this method are: I, II* or II",
    "1602": "The value you supplied in the 'listed_after' filter variable was not valid. This value needs to be a valid year in YYYY format, eg 1975.",
    "1701": "You did not provide the id for a property, as returned by the /sourced-properties API method.",
    "1702": "The property_id value you supplied was not in the expected format. The property_id parameter should match an id for a property as returned by the /sourced-properties API method.",
    "1703": "The property could not be found on our Sourcing lists. Either this property has been removed from the market or there is an error in the provided property_id.",
    "1801": "The named field is missing. All fields are required for development calculation.",
    "1802": "The named field is present but is not valid. This field must be a numeric value without any unit prefix or suffix, eg: 100000.",
    "1803": "The value you supplied for this field was not valid. Valid values for this field are: refurbish, demolition",
    "1804": "The value you supplied for this field was not valid. Valid values for this field are: house, block_of_flats",
    "1805": "The value you supplied for this field was not valid. Valid values for this field are: premium, medium, basic",
    "1901": "You did not provide the title input. A valid land title number is required for this method",
    "1902": "The land title number you provided for this method is not valid. Land title numbers can be found using the /freehold-titles API method",
    "1903": "We are unable to provide a building analysis for this title plot",
    "2000": "We are unable to determine the planning use class for this land registry title",
    "2100": "We are unable to find a UPRN record with the provided UPRN"
}
